coisa = input('Digite algo:')
print('O tipo primitivo desse valor é', type(coisa))
print('Só tem espços?', coisa.isspace())
print('É um número?', coisa.isnumeric())
print('É alfabético?', coisa.isalpha())
print('É alfanumérico?', coisa.isalnum())
print('Está em maiusculas?', coisa.isupper())
print('Está em minusculas?', coisa.islower())
print('Está capitalizada?', coisa.istitle())